### DISCUSSION TITLE
XDEBUG config is not working for vscode.

### DISCUSSION THREAD

**Discussion by rehanawan** [craftcms/docker#54] [General] [answered]
Can some one please share the launch.json for xdebug in VSCODE? 

**using:** image: craftcms/nginx:7.4-dev

**docker-compose**
```
web:
    image: craftcms/nginx:7.4-dev
    depends_on:
      - composer
    volumes:
      - ./web:/var/www/html/web
      - ./plugins:/var/www/html/plugins
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_MAX_EXECUTION_TIME: 30
      PHP_UPLOAD_MAX_FILESIZE: 40M
      PHP_MAX_INPUT_VARS: 1000
      PHP_POST_MAX_SIZE: 40M
      PHP_OPCACHE_ENABLE: 0
    ports:
      - 9081:80 
```

**launch.json:**
```

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            // "stopOnEntry": true,
            "log": true,
            "pathMappings": {
                "/var/www/html": "${workspaceRoot}/",
                // "/app": "${workspaceFolder}/app"
              }
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
        }
    ]
}
```
