### ISSUE TITLE
Unable to install Craft Commerce

### ISSUE THREAD

**Issue by samjbobb** [craftcms/docker#11]
### Description

I was unable to install the Craft Commerce plugin when running Craft using these docker containers.

### Steps to reproduce

1. Setup Craft using the Docker Compose file suggested in this repo (I've also included mine below)
1. Run `docker-compose up` and go through the Craft setup process
1. Navigate to the Plugin Store in Craft and attempt to install the Commerce plugin OR run `composer require craftcms/commerce` -- both produce the same result.

I received the following error:

```
Using version ^3.2 for craftcms/commerce
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - craftcms/commerce 3.2.1 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.2 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.2.1 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.3 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.4 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.5 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.6 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.7 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
    - craftcms/commerce 3.2.0 requires dompdf/dompdf ^0.8.4 -> satisfiable by dompdf/dompdf[v0.8.4, v0.8.5, v0.8.6].
    - craftcms/commerce 3.2.0.1 requires dompdf/dompdf ^0.8.4 -> satisfiable by dompdf/dompdf[v0.8.4, v0.8.5, v0.8.6].
    - craftcms/commerce 3.2.0.2 requires dompdf/dompdf ^0.8.4 -> satisfiable by dompdf/dompdf[v0.8.4, v0.8.5, v0.8.6].
    - ibericode/vat 1.2.1 requires php >=7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - ibericode/vat 1.2.0 requires php >=7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - ibericode/vat 1.1.3 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - ibericode/vat 1.1.2 requires ext-soap * -> the requested PHP extension soap is missing from your system.
    - dompdf/dompdf v0.8.6 requires php ^7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - dompdf/dompdf v0.8.5 requires php ^7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - dompdf/dompdf v0.8.4 requires php ^7.1 -> your PHP version (7.4.11) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - Installation request for craftcms/commerce ^3.2 -> satisfiable by craftcms/commerce[3.2.0, 3.2.0.1, 3.2.0.2, 3.2.1, 3.2.2, 3.2.2.1, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php-cli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
```

I resolved this issue by removing the `platform` directive from `composer.json` via `composer config platform --unset`.

Repeating the above attempt to install the Commerce plugin, I now get:

```
Composer was unable to install the updates due to a dependency conflict.

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- ibericode/vat 1.2.1 requires ext-soap * -> the requested PHP extension soap is missing from your system.
- ibericode/vat 1.2.0 requires ext-soap * -> the requested PHP extension soap is missing from your system.
- ibericode/vat 1.1.3 requires ext-soap * -> the requested PHP extension soap is missing from your system.
- ibericode/vat 1.1.2 requires ext-soap * -> the requested PHP extension soap is missing from your system.
- craftcms/commerce 3.2.7 requires ibericode/vat ^1.1.2 -> satisfiable by ibericode/vat[1.1.2, 1.1.3, 1.2.0, 1.2.1].
- Installation request for craftcms/commerce 3.2.7 -> satisfiable by craftcms/commerce[3.2.7].

To enable extensions, verify that they are enabled in your .ini files:
-
- /usr/local/etc/php/conf.d/craft-cms.ini
- /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
- /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini
- /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
- /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
- /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
- /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini
- /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
- /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
- /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
- /usr/local/etc/php/conf.d/xdebug.ini
You can also run php --ini inside terminal to see which files are used by PHP in CLI mode.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

I then resolved that problem by installing the Soap extension manually in the `php-fpm` container:

```
% docker-compose exec --user root php-fpm sh

# apk add libxml2-dev

# docker-php-ext-install soap

# exit

% docker-compose restart php-fpm 
```

I was then able to successfully install the Commerce plugin.

### Possible Resolution

I think that this would be resolved by adding the following to the [Dockerfile here](https://github.com/craftcms/docker/blob/7.4/Dockerfile#L5-L40)

`apk add libxml2-dev`

`docker-php-ext-install soap` 

Happy to make a pull request with those changes but would like to know that I'm on the right track first and haven't overlooked something simpler. 

### Additional info

PHP version	7.4.11
OS version	Linux 4.19.76-linuxkit
Database driver & version	MySQL 8.0.21
Image driver & version	Imagick 3.4.4 (ImageMagick 7.0.10-25)
Craft edition & version	Craft Solo 3.5.12.1
Yii version	2.0.38
Twig version	2.13.1
Guzzle version	6.5.5
Imagine version	1.2.3-dev

My Docker Compose file:

```
cat docker-compose.yml 
version: "3.6"
services:
  php-fpm:
    image: craftcms/php-fpm:7.4-dev
    volumes:
      - .:/app
#    env_file: .env
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
  console:
    image: craftcms/cli:7.4-dev
    volumes:
      - .:/app
#    env_file: .env
    command: ["./craft", "queue/listen"]
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword123456!
      MYSQL_DATABASE: dev_craftcms
      MYSQL_USER: craftcms
      MYSQL_PASSWORD: SecretPassword
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
volumes:
  db_data:
```
