### ISSUE TITLE
Add Github Actions to use Matrix Builds

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/docker#14]
Buildkit does not support subdirectories. As soon as https://github.com/moby/buildkit/issues/1684 is resolved, we can use a single `build.yml` for all building and pushing all images:

```
name: Docker Build
on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
    name: build - ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push php-fpm:${{ matrix.php }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ./${{ matrix.php }}/Dockerfile
          push: true
          tags: craftcms/php-fpm:${{ matrix.php }}
          build-args: |
            PROJECT_TYPE=fpm
            PHP_VERSION=${{ matrix.php }}
      - name: Build and push php-fpm:${{ matrix.php }}-dev
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}
          file: ./${{ matrix.php }}/dev.Dockerfile
          push: true
          tags: craftcms/php-fpm:${{ matrix.php }}-dev
          build-args: |
            PROJECT_TYPE=php-fpm
            PHP_VERSION=${{ matrix.php }}
```
