### ISSUE TITLE
Make Nginx document root configurable

### ISSUE THREAD

**Issue by michaelrog** [craftcms/docker#77]
It'd be super helpful for the PHP/Nginx images to allow customizing the document root by env variable.

Something like:
```
web:
  image: craftcms/nginx:8.1
  ports:
    - "8080:8080"
  environment:
    PHP_MEMORY_LIMIT: 512M
    ...
    NGINX_DOCUMENT_ROOT: "/web"
    depends_on:
      - "mysql"
    volumes:
      - .:/app
```
